---
- name: Change ssh port to Non default
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Change Port
      register: sshd_config
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '^Port'
        line: "Port 10123"
    - name: Restart ssh
      systemd:
        name: ssh
        enabled: true
        state: restarted
      when: sshd_config is changed