---
- name: Create User with sudo
  hosts: all
  become: true
  become_method: sudo
  vars:
    new_user_name: "{{ lookup('ansible.builtin.env', 'USER', default=Undifined) }}"
    new_user_ssh_key: "{{ lookup('ansible.builtin.env','USER_SSH_KEY', default=Undifined) }}"
  tasks:
    - name: Add user
      user:
        shell: "/bin/bash"
        name: "{{ new_user_name }}"
        password: "!"
    - name: Add ssh key
      when: new_user_ssh_key is defined
      authorized_key:
        key: "{{ new_user_ssh_key }}"
        user: "{{ new_user_name }}"
    - name: Add user to sudoers directory
      copy:
        content: '{{ new_user_name }} ALL=(ALL) NOPASSWD:ALL'
        dest: "/etc/sudoers.d/{{ new_user_name }}"
        mode: 0440
